//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("frontend.Resources.Languages.HomeL", typeof(HomeL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! My name is Gados Márk and  I&apos;m the developer behind &lt;strong&gt;Postwall&lt;/strong&gt;..
        /// </summary>
        public static string CreatorMessageLine1 {
            get {
                return ResourceManager.GetString("CreatorMessageLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project was built to make flyer browsing easier and more accessible..
        /// </summary>
        public static string CreatorMessageLine2 {
            get {
                return ResourceManager.GetString("CreatorMessageLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any trouble or something odd is happenning, feel free to reachout..
        /// </summary>
        public static string CreatorMessageLine3 {
            get {
                return ResourceManager.GetString("CreatorMessageLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for visiting!.
        /// </summary>
        public static string CreatorMessageLine4 {
            get {
                return ResourceManager.GetString("CreatorMessageLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enjoy my work, please give a star on my .
        /// </summary>
        public static string GithubIntro {
            get {
                return ResourceManager.GetString("GithubIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repository! :).
        /// </summary>
        public static string GithubOutro {
            get {
                return ResourceManager.GetString("GithubOutro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Latest Flyers.
        /// </summary>
        public static string LatestFlyers {
            get {
                return ResourceManager.GetString("LatestFlyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse weekly deals from your favorite supermarkets all in one place..
        /// </summary>
        public static string UnderWelcomeMessage {
            get {
                return ResourceManager.GetString("UnderWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Lidl.
        /// </summary>
        public static string VisitLidl {
            get {
                return ResourceManager.GetString("VisitLidl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Penny.
        /// </summary>
        public static string VisitPenny {
            get {
                return ResourceManager.GetString("VisitPenny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Spar.
        /// </summary>
        public static string VisitSpar {
            get {
                return ResourceManager.GetString("VisitSpar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Postwall!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
